[pytest]
addopts =
    --browser chromium
    --headed
    --slowmo 100
    --screenshot on
    --video retain-on-failure
    --tracing retain-on-failure
    --video retain-on-failure
    --output test-results/
base_url =  http://localhost:8080/en-US/